### ISSUE TITLE
Add translation support

### ISSUE THREAD

**Issue by smartcorestudio** [smoqadam/background-image-ckeditor-plugin#2]
Now your plugin doesn't support i18n. If you'll add this abitity I can add a translation

**Comment by smoqadam** [comment]
I will appreciate it if you add translation.
thanks

**Comment by smartcorestudio** [comment]
But it seems that your plugin doesn't support translation. In onter plugins there are separate language files such as `en.js`, `fr.js`, `de.js` etc.

**Comment by smoqadam** [comment]
The plugin now support translation. You can add your language.
:+1:

**Comment by smoqadam** [comment]
Thanks for PR
